# 데이터 분석
## 배열(NumPy)
## 데이터프레임(Pandas)

In [1]:
# 리스트(List)
lst = list(range(10))
print(lst)
print(lst * 2)

result = []
for num in lst:
    result.append(num * 2)

print(result)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [2]:
import numpy as np
# 배열(Array)
arr = np.arange(10)
print(arr)
print(arr * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]

In [3]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
# 결측치 개수 확인
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [6]:
# 주요 통계 지표(숫자 타입)
# 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 분위수(25%, 50%, 75%), 최댓값(max)
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [7]:
# 중볻값 확인
df.duplicated().sum()

np.int64(1)

In [8]:
df[df.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [9]:
# 카테고리 타입의 값 확인
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [10]:
# smoker 유형에 따라 각 수치형 변수의 평균값 출력
# Pandas  2.0 버전 이후는 카테고리 유형이 자동 배제되지 않는다
df.groupby(['smoker']).mean(numeric_only=True)

        total_bill       tip      size
smoker
Yes      20.756344  3.008710  2.408602
No       19.188278  2.991854  2.668874

In [ ]:
# 머신러닝 알고리즘은 모든 데이터가 수직형 데이터일 경우에만 학습 가능
# 원핫 인코딩 -> 카테고리형 데이터를 수치형 데이터로 변환
pd.get_dummies(df, dtype=int).head()

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,0,1,0,1,0,0,0,1,0,1
1,10.34,1.66,3,1,0,0,1,0,0,0,1,0,1
2,21.01,3.50,3,1,0,0,1,0,0,0,1,0,1
3,23.68,3.31,2,1,0,0,1,0,0,0,1,0,1
4,24.59,3.61,4,0,1,0,1,0,0,0,1,0,1