# 데이터 분석
## 배열(NumPy)
## 데이터프레임(Pandas)

In [1]:
# 리스트(List)
lst = list(range(10))
print(lst)
print(lst * 2)

result = []
for num in lst:
    result.append(num * 2)
print(result)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [2]:
import numpy as np
# 배열(Array)
arr = np.arange(10)
print(arr)
print(arr * 2)

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]

In [3]:
import pandas as pd
import seaborn as sns

df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [5]:
# 결측치 개수 확인
df.isna().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [6]:
print(True + True)
print(True + False)
print(False + False)

2
1
0

In [7]:
# 주요 통계 지표(숫자 타입)
# 개수(count), 평균(mean), 표준편차(std), 최솟값(min), 분위수(25%, 50%, 75%), 최댓값(max)
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
# 중복값 확인
df.duplicated().sum()

np.int64(1)

In [9]:
df[df.duplicated()]

     total_bill  tip     sex smoker   day   time  size
202        13.0  2.0  Female    Yes  Thur  Lunch     2

In [10]:
# 카테고리 타입의 값 확인
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [11]:
# smoker 유형에 따라 각 수치형 변수의 평균값 출력
# Pandas 2.0 버전 이후는 카테고리 유형이 자동 배제되지 않는다.
df.groupby(['smoker']).mean(numeric_only=True)

        total_bill       tip      size
smoker
Yes      20.756344  3.008710  2.408602
No       19.188278  2.991854  2.668874

In [12]:
!pip list

Package                   Version
------------------------- -----------
absl-py                   2.5.0
altair                    6.2.2
anyio                     4.14.2
asttokens                 3.0.2
astunparse                1.6.3
attrs                     26.1.0
beautifulsoup4            4.15.0
blinker                   1.9.0
cachetools                7.1.4
certifi                   2026.6.17
cffi                      2.1.0
charset-normalizer        3.4.9
click                     8.4.2
colorama                  0.4.6
comm                      0.2.3
contourpy                 1.3.3
curl_cffi                 0.15.0
cycler                    0.12.1
debugpy                   1.8.21
decorator                 5.3.1
et_xmlfile                2.0.0
executing                 2.2.1
fastjsonschema            2.21.2
flatbuffers               25.12.19
fonttools                 4.63.0
gast                      0.7.0
gitdb                     4.0.12
GitPython                 3.1.52
google-pasta              0.2.0
grpcio                    1.82.1
h11                       0.16.0
h5py                      3.14.0
httptools                 0.8.0
idna                      3.18
ipykernel                 7.3.0
ipython                   9.15.0
ipython_pygments_lexers   1.1.1
itsdangerous              2.2.0
jedi                      0.20.0
Jinja2                    3.1.6
joblib                    1.5.3
jsonschema                4.26.0
jsonschema-specifications 2025.9.1
jupyter_client            8.9.1
jupyter_core              5.9.1
jupytext                  1.19.5
keras                     3.15.0
kiwisolver                1.5.0
libclang                  18.1.1
lxml                      6.1.1
markdown-it-py            4.2.0
MarkupSafe                3.0.3
matplotlib                3.11.1
matplotlib-inline         0.2.2
mdit-py-plugins           0.6.1
mdurl                     0.1.2
ml_dtypes                 0.5.4
multitasking              0.0.13
namex                     0.1.0
narwhals                  2.24.0
nbformat                  5.10.4
nest-asyncio2             1.7.2
numpy                     2.4.6
openpyxl                  3.1.5
opt_einsum                3.4.0
optree                    0.19.1
outcome                   1.3.0.post0
packaging                 26.2
pandas                    3.0.3
parso                     0.8.7
peewee                    4.2.6
pillow                    12.3.0
pip                       26.1.2
platformdirs              4.10.1
plotly                    6.9.0
prompt_toolkit            3.0.52
protobuf                  7.35.1
psutil                    7.2.2
pure_eval                 0.2.3
pyarrow                   24.0.0
pycparser                 3.0
pydeck                    0.9.3
Pygments                  2.20.0
PyMySQL                   1.2.0
pyparsing                 3.3.2
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-dotenv             1.2.2
python-multipart          0.0.32
pytz                      2026.2
PyYAML                    6.0.3
pyzmq                     27.1.0
referencing               0.37.0
requests                  2.34.2
rich                      15.0.0
rpds-py                   2026.6.3
scikit-learn              1.9.0
scipy                     1.17.1
seaborn                   0.13.2
selenium                  4.46.0
setuptools                83.0.0
six                       1.17.0
smmap                     5.0.3
sniffio                   1.3.1
sortedcontainers          2.4.0
soupsieve                 2.9
stack-data                0.6.3
starlette                 1.3.1
streamlit                 1.59.2
streamlit-autorefresh     1.0.1
tenacity                  9.1.4
tensorflow                2.21.0
termcolor                 3.3.0
threadpoolctl             3.6.0
toml                      0.10.2
tornado                   6.5.7
traitlets                 5.15.1
trio                      0.33.0
trio-websocket            0.12.2
typing_extensions         4.16.0
tzdata                    2026.3
urllib3                   2.7.0
uvicorn                   0.51.0
watchdog                  6.0.0
wcwidth                   0.8.2
websocket-client          1.9.0
websockets                16.1.1
wheel                     0.47.0
wrapt                     2.2.2
wsproto                   1.3.2
yfinance                  1.5.1

In [13]:
!pip show pandas

Name: pandas
Version: 3.0.3
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author:
Author-email: The Pandas Development Team <pandas-dev@python.org>
License: BSD 3-Clause License

 Copyright (c) 2008-2011, AQR Capital Management, LLC, Lambda Foundry, Inc. and PyData Development Team
 All rights reserved.

 Copyright (c) 2011-2026, Open source contributors.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 * Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.

 * Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.

 * Neither the name of the copyright holder nor the names of its
   contributors may be used to endorse or promote products derived from
   this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Location: E:\wi\git\big0611\.venv\Lib\site-packages
Requires: numpy, python-dateutil, tzdata
Required-by: seaborn, streamlit, yfinance

In [16]:
# 머신러닝 알고리즘은 모든 데이터가 수치형 데이터일 경우에만 학습 가능
# 원핫 인코딩 -> 카테고리형 데이터를 수치형 데이터로 변환
pd.get_dummies(df, dtype=int)

,total_bill,tip,size,sex_Male,sex_Female,smoker_Yes,smoker_No,day_Thur,day_Fri,day_Sat,day_Sun,time_Lunch,time_Dinner
0,16.99,1.01,2,0,1,0,1,0,0,0,1,0,1
1,10.34,1.66,3,1,0,0,1,0,0,0,1,0,1
2,21.01,3.50,3,1,0,0,1,0,0,0,1,0,1
3,23.68,3.31,2,1,0,0,1,0,0,0,1,0,1
4,24.59,3.61,4,0,1,0,1,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,3,1,0,0,1,0,0,1,0,0,1
240,27.18,2.00,2,0,1,1,0,0,0,1,0,0,1
241,22.67,2.00,2,1,0,1,0,0,0,1,0,0,1
242,17.82,1.75,2,1,0,0,1,0,0,1,0,0,1
243,18.78,3.00,2,0,1,0,1,1,0,0,0,0,1