In [1]:
# 데이터 통합

In [2]:
import pandas as pd

In [3]:
# 두 개의 통합혈 데이터프레임
df1 = pd.DataFrame({
    'ID': ['1', '2', '3'],
    'Name': ['Alice', 'Bob', 'Charlie']
})

df2 = pd.DataFrame({
    'ID': ['4', '5', '6'],
    'Name': ['David', 'Eva', 'Frank']
})

In [4]:
df1

  ID     Name
0  1    Alice
1  2      Bob
2  3  Charlie

In [5]:
df2

  ID   Name
0  4  David
1  5    Eva
2  6  Frank

In [6]:
# 데이터프레임 df1과 df2를 행(Row) 기준으로 연결(위아래로 붙이기)
result_concat = pd.concat([df1, df2], axis=0, ignore_index=True)
print(result_concat)

  ID     Name
0  1    Alice
1  2      Bob
2  3  Charlie
3  4    David
4  5      Eva
5  6    Frank

In [ ]:
# ignore_index=True -> 기존 인덱스 무시
# axis 기본값은 0(위에서 아래로 붙이기)
pd.concat([df1, df2], axis=0, ignore_index=True)

In [ ]:
# 데이터 열 기준 결합
df3 = pd.DataFrame({
    'age': [25, 30, 35]
})
df3